
@token=yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MDBmM2E0Ni1jZjA5LTQwZGQtYjQ1NS1kMDM2YjNiYmFhYTciLCJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJDcmlzcGluIiwiZmFtaWx5X25hbWUiOiJUdWJhbGxhIiwianRpIjoiYjc5OTRlZTUtMjlhMS00YjNhLThlMzAtODNiMTlkNjk5OWE0IiwiZXhwIjoxNjgwNDg3NjY4LCJpc3MiOiJrY3QtaW1zIiwiYXVkIjoia2N0LWltcyJ9.tYEZhvr_fZRM0DVgVfD8jKSI9NXQRwl5rQ3y3Fjk52c

###
POST http://localhost:5236/auth/register
Content-Type: application/json
X-Version: 1.1

{
    "firstName": "Crispin",
    "lastName": "Tuballa",
    "email": "email@email.com",
    "password": "password123"
}

###
POST http://localhost:5236/auth/login
Content-Type: application/json
X-Version: 1.1

{
    "email": "email@email.com",
    "password": "password123"
}